# ipsec.conf - strongSwan IPsec configuration file

config setup
    uniqueids=never # Разрешить несколько подключений под одним логином
    charondebug="ike 2, knl 2, cfg 2" # Логи для отладки

conn ikev2-vpn
    auto=add #ожидает подключения клиента, сам не инициирует его, если должен сам подключаться то `start`
    compress=no #не сжимать трафик
    type=tunnel #говорит что создаётся тунель между клиентом и сервером а связь между сервером и сервером былабы (transoprt)
    keyexchange=ikev2 #тип тунеля
    fragmentation=yes #самому ему разбивать пакеты если MTU по пути узкий
    forceencaps=yes #инкапсуляция и маскировка ESP трафика под UDP
    
# Две стороны подключения
    # left = сервер
    left=%any #Слушать на всех сетевых интерфейсах сервера
    leftid=@vpn.mydomain.com # доменное имя сервера (или его адрес), @ говорит не пытаться разрешить это доменное имя, а воспринять просто как текст
    leftcert=server-cert.pem # сертификат сервера, либо сгенерированный, либо публичный домена
    leftsendcert=always # сервер даёт свой сертификат для проверки
    leftsubnet=0.0.0.0/0 # Пускать весь трафик через VPN
    
    # right = клиент
    right=%any # разрешаем подключаться клиентм с любых адресов, без ограничений
    rightid=%any # не важно какое имя, важен пароль
    rightauth=eap-mschapv2 # Авторизация по логину/паролю
    rightsourceip=10.10.10.0/24 # Виртуальная сеть для клиентов
    rightdns=172.16.10.2, 172.16.10.3 # днс сервера для для клиентов
    rightsendcert=never # сам клиент не даёт сертификат для проверки
    eap_identity=%identity # для авторизации пользователя использовать логин и пароль, логин использовать тотже когда клиент представляется перед сервером
