version: "3.5"
services:
  squid:
    build: ./squid
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - RC=${RC}
  tor: 
    build: ./tor
    restart: unless-stopped
    deploy:
      replicas: ${RC}
    environment:
      - TZ=${TZ}
  privoxy: 
    build: ./privoxy
    restart: unless-stopped
    deploy:
      replicas: ${RC}
    environment:
      - TZ=${TZ}
    volumes:
      - ./conf/privoxy.conf:/etc/privoxy/privoxy.conf:ro
      - ./conf/tor-rs.sh:/etc/privoxy/tor-rs.sh:ro
    entrypoint: ["/etc/privoxy/tor-rs.sh"]