#
# Proxy server for CNPPM employees
#
services:
  tor:
    image: glogol/tor-privoxy:latest
    deploy:
      mode: replicated
      replicas: 2
    configs:
      - source: torrc
        target: /etc/tor/torrc.example
        uid: "101"
        gid: "102"
        mode: 0400
      - source: obfsList
        target: /etc/tor/torList
        uid: "101"
        gid: "102"
        mode: 0400
      - source: privoxy
        target: /etc/privoxy/config
        uid: "100"
        gid: "101"
        mode: 0660
      - source: bridgeSelection
        target: /etc/tor/bst.sh
        uid: "101"
        gid: "102"
        mode: 0400
    environment:
      BRIDGES_COUNT: 2
    command: ["sh", "-c", "sh /etc/tor/bst.sh && /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf"]
    healthcheck:
      test: ["CMD", "curl", "--socks5-hostname", "127.0.0.1:9050", "-fsS", "--connect-timeout", "10", "https://check.torproject.org/"]
      interval: 30s
      timeout: 15s
      retries: 2
      start_period: 90s
  haproxy:
    image: glogol/haproxy:latest
    hostname: haproxy
    deploy:
      mode: global
    configs:
      - source: haproxy
        target: /etc/haproxy/haproxy.cfg
        uid: "99"
        gid: "99"
        mode: 0400
  squid:
    image: glogol/squid:latest
    dns:
      - 172.16.10.2
      - 172.16.10.3
    hostname: squid
    environment:
      TZ: Europe/Moscow
    deploy:
      mode: global
    ports:
    - target: 3128
      published: 31288
      protocol: tcp
      mode: host
    - target: 3128
      published: 31288
      protocol: udp
      mode: host
    configs: 
    - source: squid
      target: /etc/squid/squid.conf
      uid: "0"
      gid: "0"
      mode: 0644
    - source: proxylist
      target: /etc/squid/tor-acl
      uid: "0"
      gid: "0"
      mode: 0644
    - source: non-prohibited
      target: /etc/squid/non-prohibited
      uid: "0"
      gid: "0"
    - source: eventslist
      target: /etc/squid/events
      uid: "0"
      gid: "0"
    volumes:
    - type: bind
      source: ./squid/ru-ru
      target: /usr/share/squid/errors/ru-ru
configs:
  torrc:
    file: ./tor/torrc
  obfsList:
    file: ./.bridges
  privoxy:
    file: ./tor/privoxy
  bridgeSelection:
    file: ./tor/bst.sh
  haproxy:
    file: ./haproxy/config
  squid:
    file: ./squid/squid.conf
  proxylist:
    file: ./squid/tor-acl
  non-prohibited:
    file: ./squid/non-prohibited
  eventslist:
    file: ./squid/events