FROM alpine:latest
LABEL maintainer="alisterosenheim@outlook.com"
RUN apk --no-cache add tzdata curl squid squid-lang-ru
EXPOSE 3128/tcp
EXPOSE 3128/udp
CMD ["/usr/sbin/squid", "-N", "-f", "/etc/squid/squid.conf"]