# Localnets
acl localnet src 0.0.0.1-0.255.255.255	# RFC 1122
acl localnet src 10.0.0.0/8		        # RFC 1918
acl localnet src 100.64.0.0/10		    # RFC 6598
acl localnet src 169.254.0.0/16 	    # RFC 3927
acl localnet src 172.16.0.0/12		    # RFC 1918
acl localnet src 192.168.0.0/16		    # RFC 1918
acl localnet src fc00::/7       	    # RFC 4193
acl localnet src fe80::/10      	    # RFC 4291

acl auditories src 172.16.12.0/25
acl auditories src 172.16.12.128/25

# Full Access
acl fa src 172.16.10.0/26               # Managment LAN
acl fa src 192.168.0.0/24               # VIRO       
acl fa src 172.18.0.1                   # Home Mike PC

# Limited Access Networks
acl la src 172.16.11.0/26               # Employees
acl la src 172.16.12.0/25               # Auditories
acl la src 172.16.12.128/25             # Wi-Fi Auditories
acl la src 172.16.13.0/24               # Wi-Fi CNPPM

# Access Controll Lists
acl tor-list dstdomain "/etc/squid/tor-acl"
acl non-prohibited dstdomain "/etc/squid/non-prohibited"
acl events dstdomain "/etc/squid/events"

# Main config: ports, core place
http_port 0.0.0.0:3128
coredump_dir /var/cache/squid

# Tor Gateway
cache_peer haproxy parent 8118 0 no-query proxy-only default name=tor-proxy login=PASSTHRU
tcp_outgoing_address 0.0.0.0

# When not to redirect the proxy yourself
never_direct allow tor-list
never_direct allow non-prohibited
always_direct allow all !tor-list !non-prohibited

# Access use tor-proxy to tor-list websites
cache_peer_access tor-proxy allow tor-list

# Access websites only from the list, or all if the list is empty
http_access allow auditories events
http_access deny auditories !events

# Full access to computers from the list "fa"
http_access allow fa

# Limited access only to sites from the allowed list and blocking the rest from the Tor list 
http_access allow la non-prohibited
http_access deny la tor-list

# Allow access from local networks and deny it from all others
http_access allow localnet
http_access deny all

# Cache
cache_dir ufs /var/cache/squid 100 16 256
refresh_pattern ^ftp:		1440	20%	10080
refresh_pattern -i (/cgi-bin/|\?) 0	0%	0
refresh_pattern .		0	20%	4320