# === ACL для сетей (Клиенты) ===
acl fullAccess src 172.16.10.0/26 172.16.10.96/27 172.16.11.0/26
acl fullAccess src 172.17.0.0/16 172.18.0.0/15 172.20.0.0/14
acl fullAccess src 192.168.0.0/24 192.168.99.0/24 10.0.0.0/16 

acl restricted src 172.16.11.128/26 172.16.12.0/25 172.16.12.128/25 172.16.13.0/24

# === Списки сайтов ===
acl wLaw dstdomain "/etc/squid/within_law"
acl wLawIp dst "/etc/squid/within_law_ip"
acl oLaw dstdomain "/etc/squid/outside_law"

# === Настройки таймаутов (под Tor) ===
# Даем время на построение цепочек в Tor
connect_timeout 60 seconds
read_timeout 5 minutes
request_timeout 2 minutes
persistent_request_timeout 1 minute
# Чтобы Squid не "хоронил" HAProxy при первой же задержке
peer_connect_timeout 20 seconds

# === Порты и кэш ===
http_port 0.0.0.0:3128
coredump_dir /var/cache/squid
cache_dir ufs /var/cache/squid 100 16 256
refresh_pattern ^ftp:          1440 20% 10080
refresh_pattern -i (/cgi-bin/|\?) 0 0% 0
refresh_pattern .             0 20% 4320

# === Родительский прокси HAProxy ===
# Убрал proxy-only, добавил connect-timeout
# proxy-surrogate - сообщает адрес источника для следующего участника цепочки, не меняя пакет, дочерний сервер должен поддерживать эту функцию
cache_peer haproxy parent 8118 0 no-query default name=tor-proxy connect-timeout=15
# Форсируем IPv4 выход для Squid
tcp_outgoing_address 0.0.0.0

# === Направление трафика (Критическая часть) ===
# 1. ЗАПРЕЩАЕМ идти напрямую для списков (это уберет HIER_DIRECT)
always_direct deny oLaw
always_direct deny wLaw
always_direct deny wLawIp
# 2. РАЗРЕШАЕМ идти напрямую для всего остального
always_direct allow all

# 3. ПРИНУДИТЕЛЬНО гоним списки в Tor
# вечно забываю, мне нужен этот коментарий
# Суть проста: Разрешаю (allow), никогда самому не перенаправлять напрямую к провайдеру (never_direct) списки
never_direct allow oLaw
never_direct allow wLaw
never_direct allow wLawIp

# Запрещаем Squid пытаться "умничать" с POST-запросами (актуально для API)
nonhierarchical_direct off

# === Доступ к родительскому прокси ===
cache_peer_access tor-proxy allow fullAccess oLaw
cache_peer_access tor-proxy allow fullAccess wLaw
cache_peer_access tor-proxy allow fullAccess wLawIp
cache_peer_access tor-proxy allow restricted wLaw
cache_peer_access tor-proxy allow restricted wLawIp
cache_peer_access tor-proxy deny all

# === HTTP Access (Кто куда может ходить) ===
http_access allow localhost
# Разрешаем полному доступу всё через Squid
http_access allow fullAccess
# Restricted может только в wLaw списки и обычный инет (кроме oLaw)
http_access allow restricted wLaw
http_access allow restricted wLawIp
http_access allow restricted !oLaw
# Все остальное в бан
http_access deny all

# Сохраняем оригинал адреса и передаём информацию о цепочке, действует только для http
forwarded_for on
via on
